services:
  webhook-service:
    build: 
      context: .
      network: host
    container_name: gitea-jenkins-webhook
    restart: always
    environment:
      - CONFIG_FILE=/etc/webhook/config.yaml
    volumes:
      - ./config.yaml:/etc/webhook/config.yaml:ro
      - ./logs:/var/log/webhook
    ports:
      - "8081:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
